runname: '202310gavi-4'
country: 'LBR'
scenario: 'campaign-default'
clean: TRUE
incid:
  num_samples: 200
  redraw: FALSE
  use_country_incid_trend: FALSE
vacc:
  targeting_strategy: affected_pop
  num_skip_years: 3
  ndoses: two
setting:
  incidence_rate_trend: FALSE
  outbreak_multiplier: FALSE
  random_seed: 1
