runname: '202310gavi-4'
country: 'BFA'
scenario: 'ocv1-ocv2-default'
clean: TRUE
incid:
  num_samples: 100
  redraw: FALSE
  use_country_incid_trend: TRUE
vacc:
  targeting_strategy: affected_pop
  num_skip_years: 3
  ndoses: two
setting:
  incidence_rate_trend: FALSE
  outbreak_multiplier: FALSE
  random_seed: 103
