runname: '202310gavi-4'
country: 'COD'
scenario: 'ocv1-ocv2-default'
clean: TRUE
campaign_cov: 0.965
incid:
  num_samples: 100
  redraw: FALSE
  use_country_incid_trend: FALSE
vacc:
  targeting_strategy: custom
  num_skip_years: 5
  ndoses: two
custom:
  use_montagu_coverage: FALSE
  output_years: c(2020, 2036)
  targeting_filename: input_data/drc_custom_targeting_2024_2026.rds
  coverage_filename: input_data/drc_custom_coverage_2024_2026.csv
  use_custom_shapefile: TRUE
  shapefile_filename: input_data/shapefiles/DRC_custom_shapefile/custom_shapefile.rds
  country_shapefile_filename: input_data/shapefiles/DRC_custom_shapefile/country_shapefile.rds
setting:
  incidence_rate_trend: FALSE
  outbreak_multiplier: FALSE
  random_seed: 103
