---
title: "Direct comparison between previous and current outputs (COD & KEN) -- direct demonstration (HTI)"
subtitle: "201910gavi-5 -- central burden estimates"
author: "JHU-Lee Modeling Group"
date: "`r Sys.time()`"
output:
  html_document: default
  pdf_document: default
---



```{r include=FALSE}
### Setup
chooseCRANmirror(ind = 77) #specify the mirror so that the packages can be successfully installed in the non-interactive way
package_list <- c("tidyverse",
                  "knitr",
                  "rstudioapi")
for (package in package_list) {
  if (!require(package = package, character.only = T)) {
    install.packages(pkgs = package, dependencies = TRUE)
    library(package = package, character.only = T)
  }
  library(package = package, character.only = T)
}



current_working_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(current_working_dir)
previous_campaign_default_output <- list.files(pattern = "^previous.*campaign-default.csv$")
previous_no_vaccination_output <- list.files(pattern = "^previous.*no-vaccination.csv$")
current_campaign_default_output <- list.files(pattern = "campaign-default.csv$")
current_campaign_default_output <- current_campaign_default_output[current_campaign_default_output!=previous_campaign_default_output]
current_no_vaccination_output <- list.files(pattern = "no-vaccination.csv$")
current_no_vaccination_output <- current_no_vaccination_output[current_no_vaccination_output!=previous_no_vaccination_output]

if (length(current_campaign_default_output) == 1 & length(current_no_vaccination_output) == 1) {
  cen_camp1  <- read_csv(paste0(previous_campaign_default_output[1]))
  cen_novax1 <- read_csv(paste0(previous_no_vaccination_output[1]))
  cen_camp2  <- read_csv(paste0(current_campaign_default_output[1]))
  cen_novax2 <- read_csv(paste0(current_no_vaccination_output[1]))
}else{
  message('There are multiple output files for the scenarios, please delete the duplicates and keep one for each scenario. ')
}

```



## Overview of cases in COD from two simulation results
```{r echo=FALSE}
###Comparison for COD
COD_camp1 <- cen_camp1 %>% 
  filter(country == 'COD') %>% 
  mutate(index = year*101 + age)
COD_camp1 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('COD-cases-campaign scenario-previous') +
  ylim(-20, 2050)

COD_camp2 <- cen_camp2 %>% 
  filter(country == 'COD') %>% 
  mutate(index = year*101 + age)
COD_camp2 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('COD-cases-campaign scenario-new') +
  ylim(-20, 2050)

COD_novax1 <- cen_novax1 %>% 
  filter(country == 'COD') %>% 
  mutate(index = year*101 + age)
COD_novax1 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('COD-cases-no vaccination scenario-previous') +
  ylim(-20, 2050)

COD_novax2 <- cen_novax2 %>% 
  filter(country == 'COD') %>% 
  mutate(index = year*101 + age)
COD_novax2 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('COD-cases-no vaccination scenario-new') +
  ylim(-20, 2050)

```



## Across-age-group cases in COD from two simulation results
```{r echo=FALSE}
COD_camp1 <- cen_camp1 %>% 
  filter(country == 'COD') %>% 
  group_by(year) %>% 
  summarise(cases = sum(cases), deaths = sum(deaths), dalys = sum(dalys)) %>% 
  select(year, cases, deaths, dalys)
COD_camp2 <- cen_camp2 %>% 
  filter(country == 'COD') %>% 
  group_by(year) %>% 
  summarise(cases2 = sum(cases), deaths2 = sum(deaths), dalys2 = sum(dalys)) %>% 
  select(year, cases2, deaths2, dalys2)
COD_camp <- full_join(COD_camp1, COD_camp2, id = 'year') %>% 
  gather(case_source, case_value, c(cases, cases2)) %>% 
  gather(death_source, death_value, c(deaths, deaths2)) %>% 
  gather(daly_source, daly_value, c(dalys, dalys2)) %>% 
  filter( (case_source == 'cases' &
           death_source == 'deaths' & 
           daly_source == 'dalys') | 
          (case_source == 'cases2' &
           death_source == 'deaths2' & 
           daly_source == 'dalys2')) %>% 
  mutate(source = case_source, cases = case_value, deaths = death_value, dalys = daly_value) %>% 
  mutate(source = case_when(source == 'cases' ~ 'Previous Simulation',
                            source == 'cases2' ~ 'New Simulation')) %>% 
  select(year, source, cases, deaths, dalys)

COD_camp %>% 
  ggplot(aes(x=year, y=cases, color = source)) +
    geom_point(size=1) + 
    theme_minimal() +
    ggtitle('COD-Campaign-Previous&New')
    


COD_novax1 <- cen_novax1 %>% 
  filter(country == 'COD') %>% 
  group_by(year) %>% 
  summarise(cases = sum(cases), deaths = sum(deaths), dalys = sum(dalys)) %>% 
  select(year, cases, deaths, dalys)
COD_novax2 <- cen_novax2 %>% 
  filter(country == 'COD') %>% 
  group_by(year) %>% 
  summarise(cases2 = sum(cases), deaths2 = sum(deaths), dalys2 = sum(dalys)) %>% 
  select(year, cases2, deaths2, dalys2)
COD_novax <- full_join(COD_novax1, COD_novax2, id = 'year') %>% 
  gather(case_source, case_value, c(cases, cases2)) %>% 
  gather(death_source, death_value, c(deaths, deaths2)) %>% 
  gather(daly_source, daly_value, c(dalys, dalys2)) %>% 
  filter( (case_source == 'cases' &
           death_source == 'deaths' & 
           daly_source == 'dalys') | 
          (case_source == 'cases2' &
           death_source == 'deaths2' & 
           daly_source == 'dalys2')) %>% 
  mutate(source = case_source, cases = case_value, deaths = death_value, dalys = daly_value) %>% 
  mutate(source = case_when(source == 'cases' ~ 'Previous Simulation',
                            source == 'cases2' ~ 'New Simulation')) %>% 
  select(year, source, cases, deaths, dalys)

COD_novax %>% 
  ggplot(aes(x=year, y=cases, color = source)) +
    geom_point(size=1) + 
    theme_minimal() +
    ggtitle('COD-NoVaccination-Previous&New')
```



## Overview of cases in KEN from two simulation results
```{r echo=FALSE}
###Comparison for KEN
KEN_camp1 <- cen_camp1 %>% 
  filter(country == 'KEN') %>% 
  mutate(index = year*101 + age)
KEN_camp1 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('KEN-cases-campaign scenario-previous') +
  ylim(-10, 375)

KEN_camp2 <- cen_camp2 %>% 
  filter(country == 'KEN') %>% 
  mutate(index = year*101 + age)
KEN_camp2 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('KEN-cases-campaign scenario-new') +
  ylim(-10, 375)

KEN_novax1 <- cen_novax1 %>% 
  filter(country == 'KEN') %>% 
  mutate(index = year*101 + age)
KEN_novax1 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('KEN-cases-no vaccination scenario-previous') +
  ylim(-10, 375)

KEN_novax2 <- cen_novax2 %>% 
  filter(country == 'KEN') %>% 
  mutate(index = year*101 + age)
KEN_novax2 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('KEN-cases-no vaccination scenario-new') +
  ylim(-10, 375)

```



## Across-age-group cases in KEN from two simulation results
```{r echo=FALSE}
KEN_camp1 <- cen_camp1 %>% 
  filter(country == 'KEN') %>% 
  group_by(year) %>% 
  summarise(cases = sum(cases), deaths = sum(deaths), dalys = sum(dalys)) %>% 
  select(year, cases, deaths, dalys)
KEN_camp2 <- cen_camp2 %>% 
  filter(country == 'KEN') %>% 
  group_by(year) %>% 
  summarise(cases2 = sum(cases), deaths2 = sum(deaths), dalys2 = sum(dalys)) %>% 
  select(year, cases2, deaths2, dalys2)
KEN_camp <- full_join(KEN_camp1, KEN_camp2, id = 'year') %>% 
  gather(case_source, case_value, c(cases, cases2)) %>% 
  gather(death_source, death_value, c(deaths, deaths2)) %>% 
  gather(daly_source, daly_value, c(dalys, dalys2)) %>% 
  filter( (case_source == 'cases' &
           death_source == 'deaths' & 
           daly_source == 'dalys') | 
          (case_source == 'cases2' &
           death_source == 'deaths2' & 
           daly_source == 'dalys2')) %>% 
  mutate(source = case_source, cases = case_value, deaths = death_value, dalys = daly_value) %>% 
  mutate(source = case_when(source == 'cases' ~ 'Previous Simulation',
                            source == 'cases2' ~ 'New Simulation')) %>% 
  select(year, source, cases, deaths, dalys)

KEN_camp %>% 
  ggplot(aes(x=year, y=cases, color = source)) +
    geom_point(size=1) + 
    theme_minimal() +
    ggtitle('KEN-Campaign-Previous&New')



KEN_novax1 <- cen_novax1 %>% 
  filter(country == 'KEN') %>% 
  group_by(year) %>% 
  summarise(cases = sum(cases), deaths = sum(deaths), dalys = sum(dalys)) %>% 
  select(year, cases, deaths, dalys)
KEN_novax2 <- cen_novax2 %>% 
  filter(country == 'KEN') %>% 
  group_by(year) %>% 
  summarise(cases2 = sum(cases), deaths2 = sum(deaths), dalys2 = sum(dalys)) %>% 
  select(year, cases2, deaths2, dalys2)
KEN_novax <- full_join(KEN_novax1, KEN_novax2, id = 'year') %>% 
  gather(case_source, case_value, c(cases, cases2)) %>% 
  gather(death_source, death_value, c(deaths, deaths2)) %>% 
  gather(daly_source, daly_value, c(dalys, dalys2)) %>% 
  filter( (case_source == 'cases' &
           death_source == 'deaths' & 
           daly_source == 'dalys') | 
          (case_source == 'cases2' &
           death_source == 'deaths2' & 
           daly_source == 'dalys2')) %>% 
  mutate(source = case_source, cases = case_value, deaths = death_value, dalys = daly_value) %>% 
  mutate(source = case_when(source == 'cases' ~ 'Previous Simulation',
                            source == 'cases2' ~ 'New Simulation')) %>% 
  select(year, source, cases, deaths, dalys)

KEN_novax %>% 
  ggplot(aes(x=year, y=cases, color = source)) +
    geom_point(size=1) + 
    theme_minimal() +
    ggtitle('KEN-NoVaccination-Previous&New')
```



## Overview of cases in HTI from new simulation results
```{r echo=FALSE}
###Comparison for HTI
HTI_camp2 <- cen_camp2 %>% 
  filter(country == 'HTI') %>% 
  mutate(index = year*101 + age)
HTI_camp2 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('HTI-cases-campaign scenario-new')

HTI_novax2 <- cen_novax2 %>% 
  filter(country == 'HTI') %>% 
  mutate(index = year*101 + age)
HTI_novax2 %>% 
  ggplot(aes(index, cases)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  theme_minimal() +
  ggtitle('HTI-cases-no vaccination scenario-new')

```



## Across-age-group cases in HTI
```{r echo=FALSE}
HTI_camp2 <- cen_camp2 %>% 
  filter(country == 'HTI') %>% 
  group_by(year) %>% 
  summarise(cases = sum(cases), deaths = sum(deaths), dalys = sum(dalys)) %>% 
  select(year, cases, deaths, dalys)

HTI_camp2 %>% 
  ggplot(aes(x=year, y=cases)) +
    geom_point(size=1, color='skyblue') + 
    theme_minimal() +
    ggtitle('HTI-Campaign') + 
    ylim(5000, 35000)



HTI_novax2 <- cen_novax2 %>% 
  filter(country == 'HTI') %>% 
  group_by(year) %>% 
  summarise(cases = sum(cases), deaths = sum(deaths), dalys = sum(dalys)) %>% 
  select(year, cases, deaths, dalys)

HTI_novax2 %>% 
  ggplot(aes(x=year, y=cases)) +
    geom_point(size=1, color='pink') + 
    theme_minimal() +
    ggtitle('HTI-NoVaccination') + 
    ylim(5000, 35000)
```


