runname: '202310gavi-4'
country: 'AFG'
scenario: 'no-vaccination'
clean: FALSE
incid:
  num_samples: 100
  redraw: FALSE
  use_country_incid_trend: TRUE
vacc:
  targeting_strategy: affected_pop
  num_skip_years: 5
  ndoses: zero
setting:
  incidence_rate_trend: TRUE
  outbreak_multiplier: FALSE
  random_seed: 103
